- name: nginx install and run
  hosts: frontend
  become: yes # root access
  tasks: 
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start nginx
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes



