- name: nginx install and run
  hosts: frontend
  become: yes # root access
  tasks: 
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: started nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: enabled nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
  - name: remove nginx package after installing
    ansible.builtin.package:
      name: "{{ nginx }}""
      state: absent





