- name: varaiables in ansibls
  hosts: local
  connection: local
  become: yes
  vars:
    COURSE: Ansible  # equal to  COURSE=Ansible in shell , shell we refer $VAR or ${var}
    DURATION: 10HR
    TRAINER: SIVAKUMAR
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{COURSE}}, Course Duration: {{DURATION}} , Trainer is {{TRAINER}}"