- name: task level varaiables
  hosts: local
  connection: local
  vars:
    COURSE: Devops with Aws
    DURATION: 120 HR
    TRAINER: SIVAKUMAR
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{COURSE}}, Course Duration: {{DURATION}}, Tariner is {{TRAINER}}"
      
  - name: print course infom again
    ansible.builtin.debug:
      msg: "Hello {{COURSE}}, Course Duration: {{DURATION}}, Trainer is:{{TRAINER}}"       
          