- name: Ansible installation
  hosts: frontend
  connection: 
  become: yes
  tasks:
  - name: installing Ansible 
    ansible.builtin.package:
      name: ansible
      state: present
  - name: starting ansible
    ansible.builtin.service:
      name: ansible
      state: started
  - name: enabled ansible
    ansible.builtin.service:
      name: ansible
      enabled: yes



    