- name: Ansible installation
  hosts: frontend
  become: yes
  tasks:
  - name: installing Ansible 
    ansible.builtin.package:
      name: ansible
      state: present

  - name: enabled ansible
    ansible.builtin.service:
      name: ansible
      enabled: yes



    