- name: conditions in Ansible
  hosts: local
  connection: local
  tasks:
  - name: print if number is less than oe equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} less than or equal to 100"
    when: NUMBER < 78
  - name: print if the number is greater than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than 100"
    when: NUMBER > 78

