- name: Ansible install & un-iunstalling packages
  hosts: frontend
  connection: local
  become: yes
  tasks:
  - name: install & un-installing packages
    ansible.builtin.package:
      name: "{{ item.name}}"
      state: "{{ item.state}}"
    loop:
    - { name: 'nginx', state: 'absent' } 
    - { name: 'mysql', state: 'installed' }
    - { name: 'zip',  state: 'present' }
    - { name: 'httpd', state: 'absent' }
    - { name: 'unzip', state: 'absent' }
  