- name: Ansible loops
  hosts: frontend
  connection: local
  become: yes
  tasks:
  - name: install & un-installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
  loops:
    - { name: 'nginx', state: 'present' } 
    - { name: 'mysql', state: 'absent' }
    - { name: 'zip',  state: 'absent' }
    - { name: 'httpd', state: 'absent' }
    - { name: 'unzip', state: 'absent' }
  