- name: Ansible shell vs command 
  hosts: frontend
  tasks:
  - name: redirect ls outpt  to files 
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
